### ISSUE TITLE
Raspberry Pi 5 and Kernel 6.x support

### ISSUE THREAD

**Issue by surak** [ArduCAM/IMX519_AK7375#3]
When trying to compile on the 2023.12 version of Raspberry Pi OS, I get:

```
make
make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-6.1.0-rpi7-rpi-2712'
  CC [M]  /home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.o
In file included from /usr/src/linux-headers-6.1.0-rpi7-common-rpi/include/media/v4l2-device.h:13,
                 from /home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:19:
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c: In function ‘imx519_open’:
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1114:50: error: ‘struct v4l2_subdev_fh’ has no member named ‘pad’
 1114 |                 v4l2_subdev_get_try_format(sd, fh->pad, IMAGE_PAD);
      |                                                  ^~
/usr/src/linux-headers-6.1.0-rpi7-common-rpi/include/media/v4l2-subdev.h:1105:40: note: in definition of macro ‘v4l2_subdev_get_try_format’
 1105 |         v4l2_subdev_get_pad_format(sd, state, pad)
      |                                        ^~~~~
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1116:50: error: ‘struct v4l2_subdev_fh’ has no member named ‘pad’
 1116 |                 v4l2_subdev_get_try_format(sd, fh->pad, METADATA_PAD);
      |                                                  ^~
/usr/src/linux-headers-6.1.0-rpi7-common-rpi/include/media/v4l2-subdev.h:1105:40: note: in definition of macro ‘v4l2_subdev_get_try_format’
 1105 |         v4l2_subdev_get_pad_format(sd, state, pad)
      |                                        ^~~~~
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1134:51: error: ‘struct v4l2_subdev_fh’ has no member named ‘pad’
 1134 |         try_crop = v4l2_subdev_get_try_crop(sd, fh->pad, IMAGE_PAD);
      |                                                   ^~
/usr/src/linux-headers-6.1.0-rpi7-common-rpi/include/media/v4l2-subdev.h:1108:38: note: in definition of macro ‘v4l2_subdev_get_try_crop’
 1108 |         v4l2_subdev_get_pad_crop(sd, state, pad)
      |                                      ^~~~~
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c: In function ‘imx519_get_pad_format’:
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1359:65: error: passing argument 2 of ‘v4l2_subdev_get_pad_format’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 1359 |                     v4l2_subdev_get_try_format(&imx519->sd, cfg, fmt->pad);
      |                                                             ^~~
      |                                                             |
      |                                                             struct v4l2_subdev_pad_config *

/usr/src/linux-headers-6.1.0-rpi7-common-rpi/include/media/v4l2-subdev.h:1105:40: note: in definition of macro ‘v4l2_subdev_get_try_format’
 1105 |         v4l2_subdev_get_pad_format(sd, state, pad)
      |                                        ^~~~~
/usr/src/linux-headers-6.1.0-rpi7-common-rpi/include/media/v4l2-subdev.h:1050:54: note: expected ‘struct v4l2_subdev_state *’ but argument is of type ‘struct v4l2_subdev_pad_config *’
 1050 |                            struct v4l2_subdev_state *state,
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c: In function ‘imx519_set_pad_format’:
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1450:67: error: passing argument 2 of ‘v4l2_subdev_get_pad_format’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 1450 |                         framefmt = v4l2_subdev_get_try_format(sd, cfg,
      |                                                                   ^~~
      |                                                                   |
      |                                                                   struct v4l2_subdev_pad_config *
/usr/src/linux-headers-6.1.0-rpi7-common-rpi/include/media/v4l2-subdev.h:1105:40: note: in definition of macro ‘v4l2_subdev_get_try_format’
 1105 |         v4l2_subdev_get_pad_format(sd, state, pad)
      |                                        ^~~~~
/usr/src/linux-headers-6.1.0-rpi7-common-rpi/include/media/v4l2-subdev.h:1050:54: note: expected ‘struct v4l2_subdev_state *’ but argument is of type ‘struct v4l2_subdev_pad_config *’
 1050 |                            struct v4l2_subdev_state *state,
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1460:67: error: passing argument 2 of ‘v4l2_subdev_get_pad_format’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 1460 |                         framefmt = v4l2_subdev_get_try_format(sd, cfg,
      |                                                                   ^~~
      |                                                                   |
      |                                                                   struct v4l2_subdev_pad_config *
/usr/src/linux-headers-6.1.0-rpi7-common-rpi/include/media/v4l2-subdev.h:1105:40: note: in definition of macro ‘v4l2_subdev_get_try_format’
 1105 |         v4l2_subdev_get_pad_format(sd, state, pad)
      |                                        ^~~~~
/usr/src/linux-headers-6.1.0-rpi7-common-rpi/include/media/v4l2-subdev.h:1050:54: note: expected ‘struct v4l2_subdev_state *’ but argument is of type ‘struct v4l2_subdev_pad_config *’
 1050 |                            struct v4l2_subdev_state *state,
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c: In function ‘__imx519_get_pad_crop’:
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1480:62: error: passing argument 2 of ‘v4l2_subdev_get_pad_crop’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 1480 |                 return v4l2_subdev_get_try_crop(&imx519->sd, cfg, pad);
      |                                                              ^~~
      |                                                              |
      |                                                              struct v4l2_subdev_pad_config *
/usr/src/linux-headers-6.1.0-rpi7-common-rpi/include/media/v4l2-subdev.h:1108:38: note: in definition of macro ‘v4l2_subdev_get_try_crop’
 1108 |         v4l2_subdev_get_pad_crop(sd, state, pad)
      |                                      ^~~~~
/usr/src/linux-headers-6.1.0-rpi7-common-rpi/include/media/v4l2-subdev.h:1070:52: note: expected ‘struct v4l2_subdev_state *’ but argument is of type ‘struct v4l2_subdev_pad_config *’
 1070 |                          struct v4l2_subdev_state *state,
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c: At top level:
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1756:27: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_state *, struct v4l2_subdev_mbus_code_enum *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_pad_config *, struct v4l2_subdev_mbus_code_enum *)’ [-Werror=incompatible-pointer-types]
 1756 |         .enum_mbus_code = imx519_enum_mbus_code,
      |                           ^~~~~~~~~~~~~~~~~~~~~
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1756:27: note: (near initialization for ‘imx519_pad_ops.enum_mbus_code’)
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1757:20: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_state *, struct v4l2_subdev_format *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_pad_config *, struct v4l2_subdev_format *)’ [-Werror=incompatible-pointer-types]
 1757 |         .get_fmt = imx519_get_pad_format,
      |                    ^~~~~~~~~~~~~~~~~~~~~
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1757:20: note: (near initialization for ‘imx519_pad_ops.get_fmt’)
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1758:20: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_state *, struct v4l2_subdev_format *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_pad_config *, struct v4l2_subdev_format *)’ [-Werror=incompatible-pointer-types]
 1758 |         .set_fmt = imx519_set_pad_format,
      |                    ^~~~~~~~~~~~~~~~~~~~~
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1758:20: note: (near initialization for ‘imx519_pad_ops.set_fmt’)
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1759:26: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_state *, struct v4l2_subdev_selection *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_pad_config *, struct v4l2_subdev_selection *)’ [-Werror=incompatible-pointer-types]
 1759 |         .get_selection = imx519_get_selection,
      |                          ^~~~~~~~~~~~~~~~~~~~
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1759:26: note: (near initialization for ‘imx519_pad_ops.get_selection’)
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1760:28: error: initialization of ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_state *, struct v4l2_subdev_frame_size_enum *)’ from incompatible pointer type ‘int (*)(struct v4l2_subdev *, struct v4l2_subdev_pad_config *, struct v4l2_subdev_frame_size_enum *)’ [-Werror=incompatible-pointer-types]
 1760 |         .enum_frame_size = imx519_enum_frame_size,
      |                            ^~~~~~~~~~~~~~~~~~~~~~
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:1760:28: note: (near initialization for ‘imx519_pad_ops.enum_frame_size’)
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c: In function ‘imx519_probe’:
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:2031:15: error: implicit declaration of function ‘v4l2_async_register_subdev_sensor_common’; did you mean ‘v4l2_async_register_subdev_sensor’? [-Werror=implicit-function-declaration]
 2031 |         ret = v4l2_async_register_subdev_sensor_common(&imx519->sd);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |               v4l2_async_register_subdev_sensor
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c: At top level:
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:2084:19: error: initialization of ‘void (*)(struct i2c_client *)’ from incompatible pointer type ‘int (*)(struct i2c_client *)’ [-Werror=incompatible-pointer-types]
 2084 |         .remove = imx519_remove,
      |                   ^~~~~~~~~~~~~
/home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.c:2084:19: note: (near initialization for ‘imx519_i2c_driver.remove’)
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.1.0-rpi7-common-rpi/scripts/Makefile.build:255: /home/surak/16mp-autofocus/IMX519_AK7375/IMX519/imx519.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.1.0-rpi7-common-rpi/Makefile:2039: /home/surak/16mp-autofocus/IMX519_AK7375/IMX519] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.0-rpi7-rpi-2712'
make: *** [Makefile:10: default] Error 2
```
