### ISSUE TITLE
Broken build on 6.6.5

### ISSUE THREAD

**Issue by rektide** [ArduCAM/IMX519_AK7375#4]
Seeing the following:

```
make
make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-6.6.15-arm64'
  CC [M]  /usr/local/src/arducam-16mp-git/AK7375/ak7375.o
/usr/local/src/arducam-16mp-git/AK7375/ak7375.c:421:10: error: ‘struct i2c_driver’ has no member named ‘probe_new’
  421 |         .probe_new = ak7375_probe,
      |          ^~~~~~~~~
/usr/local/src/arducam-16mp-git/AK7375/ak7375.c:421:22: error: initialization of ‘const struct i2c_device_id *’ from incompatible pointer type ‘int (*)(struct i2c_client *)’ [-Werror=incompatible-pointer-types]
  421 |         .probe_new = ak7375_probe,
      |                      ^~~~~~~~~~~~
/usr/local/src/arducam-16mp-git/AK7375/ak7375.c:421:22: note: (near initialization for ‘ak7375_i2c_driver.id_table’)
/usr/local/src/arducam-16mp-git/AK7375/ak7375.c:422:19: error: initialization of ‘void (*)(struct i2c_client *)’ from incompatible pointer type ‘int (*)(struct i2c_client *)’ [-Werror=incompatible-pointer-types]
  422 |         .remove = ak7375_remove,
      |                   ^~~~~~~~~~~~~
/usr/local/src/arducam-16mp-git/AK7375/ak7375.c:422:19: note: (near initialization for ‘ak7375_i2c_driver.remove’)
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-6.6.15-common/scripts/Makefile.build:248: /usr/local/src/arducam-16mp-git/AK7375/ak7375.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.6.15-common/Makefile:1938: /usr/local/src/arducam-16mp-git/AK7375] Error 2
make[1]: *** [/usr/src/linux-headers-6.6.15-common/Makefile:246: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.6.15-arm64'
make: *** [Makefile:10: default] Error 2
```
